
name: ci
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: yarn install, build
      run: |
        yarn
        yarn build

    - name: cp archive
      run: |
        rm -rf pages/lib pages/node_modules
        mkdir pages/node_modules pages/lib
        cp -a node_modules/xterm pages/node_modules
        cp -a node_modules/xterm-addon-search  pages/node_modules
        cp -a lib pages

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.deploy_key }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: pages
